### ISSUE TITLE
is it possibel for me to have better result ?

### ISSUE THREAD

**Issue by pjuchs** [EndyWon/Texture-Reformer#2]
Hello,
I tried to use what you have done to generate a body texture using in input a visage texture and their respective semantic, but the result isn't good. I think that due to the big transformation I ask, the method isn't enough advanced and appropriate to my problem, but I wanted to ask your point of view, because maybe I am doing something (with my sem image maybe).
Well at least the for the usual task it was giving great results !

![hm](https://user-images.githubusercontent.com/104215643/164744554-38937e5a-6867-48a7-ace8-7a1eca576e55.png)
![hmn_sem](https://user-images.githubusercontent.com/104215643/164744580-5054e6b5-7122-45e6-9cbb-25b9b9e8edde.png)
![smplb_semsave](https://user-images.githubusercontent.com/104215643/164744611-3f44434d-245d-4052-b473-c10516aa6428.png)
![output1](https://user-images.githubusercontent.com/104215643/164744809-89c43c8f-1ce1-4d59-a201-a18a00c73ce5.jpg)

![smplbfinal_sem](https://user-images.githubusercontent.com/104215643/164744853-7140d113-fd1d-4a93-bb0c-2361e859392f.png)
![outputf1](https://user-images.githubusercontent.com/104215643/164744896-12434645-8213-44dc-8083-10ccc21678cd.jpg)

![smplb_sem](https://user-images.githubusercontent.com/104215643/164744928-74466e3f-449c-4c99-a4a3-2327ddb84732.png)
![output](https://user-images.githubusercontent.com/104215643/164744963-af660f05-d654-4a23-93c8-3c889866b53f.jpg)

**Comment by EndyWon** [comment]
Here are two suggestions that might help you get better result. (1) Fine-tune the hyperparameters such as -coarse_psize and -fine_psize (or remove the global alignment stage). (2) Adjust the size of the inputs, e.g., resize them to 512x512 pixels.

**Comment by EndyWon** [comment]
Thanks for your interest in our work! Here are two suggestions that might help you get better result. (1) Fine-tune the hyperparameters such as -coarse_psize and -fine_psize (or remove the global alignment stage). (2) Adjust the size of the inputs, e.g., resize them to 512x512 pixels.

**Comment by pjuchs** [comment]
I have played with the parameters a bit : 
-fine_psize completely ruined the result when i touched it enough to have changes
-coarse_psize made some huge chunk of uniform colors, well it was more smooth in a way but not what I wanted

So it tried to play with the enhancement stage :
`print("Processing level 3"); content = SE(TR.e3, TR.d3, content, style, args.enhance, 0.3) 
print("Processing level 2"); content = SE(TR.e2, TR.d2, content, style, args.enhance, 0.005) 
print("Processing level 1"); content = SE(TR.e1, TR.d1, content, style, args.enhance, 0.02) `

Well dunno if I shouldn't touch it like that since there was originally a common parameter but i got that : 
![output](https://user-images.githubusercontent.com/104215643/165070689-667ad805-de4e-40f7-b2a1-8fe62b28f5ba.jpg)

Which is better, still not enough, so i will stick to a simpler method more adapted to what I need, but at least I have improved this result a bit (especially with the blue and purple added in comparison to the original style) even it feel like cheating. 
So thanks for this help, it is still a quite good result, better than the other texture transfer methods i tried.
