### ISSUE TITLE
Concat Weight, Pattern and synthesis

### ISSUE THREAD

**Issue by pjuchs** [EndyWon/Texture-Reformer#3]
Hello again, finally I am still trying to do something with your Texture-Reformer, but what I am trying to do goes (past) the limits explained in the article, in term of scaling/rotating elements.
But I am still asking  if you think it is possible use this method to generate texture by indicating (with the semantic) only one part of the style image and generate with this part a bigger texture.
By the way the goal is to use a BaselFaceModel face texture to obtain a full body texture.

I have done different things, and played with the concat weight awareness, for example :
style:
![face3d6](https://user-images.githubusercontent.com/104215643/173866956-7eea3cc6-40bf-4a17-8550-ce69b81ce369.jpg)
style_sem:
![512face3d_sem](https://user-images.githubusercontent.com/104215643/173867016-72a5a75d-7659-4c5c-b0c3-5d39981fdd29.png)
content_sem:
![b9_sem](https://user-images.githubusercontent.com/104215643/173867056-6d7611e8-3218-4b99-b318-369f0acf534d.png)
result with a patch size of 15 :
![female-i17-p15](https://user-images.githubusercontent.com/104215643/173867247-22fea8c2-0544-4f6c-8140-e32ff3b4c564.jpg)

There the result isn't perfect but it's not too slow and it's good enough just for the skin.
We can try to use the style image for the face even if again there are some readjustment problems, but we have no hair.

So I wanted to print the hair too on the same image or a different one :
![b10_sem](https://user-images.githubusercontent.com/104215643/173867994-e3c60937-638f-431b-acd2-320a18437aeb.png)
![hair_sem](https://user-images.githubusercontent.com/104215643/173868012-bc594df8-2c9c-42dd-b48f-9151311b7031.png)

But the result isn't there : 
![b10_512female_i17p15_w=50](https://user-images.githubusercontent.com/104215643/173868125-ffb4f8c7-1e21-4b59-8b54-c13b8e4288f4.jpg)
![hair_512female_i17p15_w=50](https://user-images.githubusercontent.com/104215643/173868148-49cc3915-e4ae-4934-8107-8e87cd5752b7.jpg)

It might be hard to understand what I ask there. So what i want to know is if you think it is possible to generate a texture with this method, using a small input from the style image. Either like we tried with a pattern like showed in t previous image or with a different application.
I also wanted to know if there is a way to play with the concat weight of stage I and II separately like showed in the end of the article.

I am asking you that even thought the  pattern application doesn't to seem very correct : 
Since when we don't have the pattern on the face we still have that:
![face512sanspattern](https://user-images.githubusercontent.com/104215643/173869696-45d44566-7255-4397-b9f7-023e3e52c811.png)
![b9_sem](https://user-images.githubusercontent.com/104215643/173869726-ff63042d-1278-4b6c-8916-77c242138230.png)
![b9_512female_0p](https://user-images.githubusercontent.com/104215643/173869747-a38c9399-bd71-4900-8620-fe9b0a08ffe9.jpg)

And this is with the pattern, there is a difference but not as big as i would think :
![512face3d_sem](https://user-images.githubusercontent.com/104215643/173870026-cad80618-5132-4c06-aee4-dc43a4dc5698.png)
![b9_sem](https://user-images.githubusercontent.com/104215643/173870081-0b9c0518-a091-4e0c-a005-ccd08f1d7deb.png)
![b9_512female_1p](https://user-images.githubusercontent.com/104215643/173870146-7fe7a713-2c86-455a-988c-82e89b943438.jpg)

The black dot have still some use cause if there is only green it does that :
![face512sanspattern](https://user-images.githubusercontent.com/104215643/173870522-565991b6-1f05-4f86-8141-50dc528771b3.png)
![green_sem](https://user-images.githubusercontent.com/104215643/173870539-aceff1eb-0963-4d1d-86e3-a190ca80ab7d.png)
![green_512female_0p](https://user-images.githubusercontent.com/104215643/173870553-d52af022-1c33-46fc-836a-528979bb1653.jpg)

Well I hope you can help me again, and I am sorry for the chaos of my questions and explanations.

**Comment by EndyWon** [comment]
Thanks for the questions. I tried to understand your questions. My suggestions are as follows:
(1) Removing the global alignment stage I, and using the local stage II only;
(2) Cropping your wanted texture region from the style image, and using the cropped image as the new style image (with proper size);
(3) If you want to play with the concat weight of stage I and II separately, just modify the codes in Line123-158 and Line199/202 in transfer.py.

Hope these could help you, good luck!
