### ISSUE TITLE
Virtual texture manipulation

### ISSUE THREAD

**Issue by opendeeple** [EndyWon/Texture-Reformer#4]
### Hello, I have tested your texture reformer for transfer texture from a mask to another.
Inputs:
-content_sem
![front-target-mask](https://user-images.githubusercontent.com/74002741/233513860-091184e2-7797-4e27-be26-a194c211e5d2.png)
-style
![front-image](https://user-images.githubusercontent.com/74002741/233513891-1e24ae37-ad1a-461e-983f-e1b065e5ae43.png)
-style_sem
![front-mask](https://user-images.githubusercontent.com/74002741/233513922-b1377cd8-16b4-4d66-9880-3cfe191c69c1.png)
Command to run:
```
python3 transfer.py -style_transfer -content_sem inputs/front-target-mask.png -style inputs/front-image.png -style_sem inputs/front-mask.png
```
And I am getting unexpected value
Output image
![output](https://user-images.githubusercontent.com/74002741/233514102-35c81901-ea80-43df-9e6c-de2a2ec63d80.jpg)

Can your help me to improve result? 
Thanks for your attention!

**Comment by EndyWon** [comment]
Sorry for the late reply, you can improve the result by adjusting the hyper-parameters, such as image size, patch size at different stage, etc.
